# Generated by hand to add CustomerOrder model and link existing orders.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_cart_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("order_number", models.CharField(max_length=20, unique=True)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=20)),
                ("shipping_address", models.JSONField()),
                ("subtotal", models.DecimalField(max_digits=12, decimal_places=2)),
                ("shipping_fee", models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ("tax_amount", models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ("total_amount", models.DecimalField(max_digits=12, decimal_places=2)),
                (
                    "payment_status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                    ),
                ),
                ("payment_reference", models.CharField(max_length=100, unique=True)),
                ("paystack_reference", models.CharField(max_length=100, blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="customer_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="orders.customerorder",
            ),
        ),
    ]

