# Generated by Django 5.2.9 on 2026-01-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='products.product'),
        ),
        migrations.AddField(
            model_name='attributiontracking',
            name='first_click_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_click_attributions', to='affiliates.affiliatelink'),
        ),
        migrations.AddField(
            model_name='attributiontracking',
            name='last_click_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_click_attributions', to='affiliates.affiliatelink'),
        ),
        migrations.AddField(
            model_name='attributiontracking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='clicktracking',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliates.affiliatelink'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliatelink',
            unique_together={('marketer', 'product')},
        ),
    ]
