# Generated by Django 5.2.9 on 2026-01-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('generated_content', models.TextField()),
                ('platform', models.CharField(max_length=50)),
                ('tone', models.CharField(max_length=50)),
                ('was_used', models.BooleanField(default=False)),
                ('feedback_rating', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('recommendation_reason', models.TextField(blank=True, null=True)),
                ('match_factors', models.JSONField(blank=True, default=dict)),
                ('was_promoted', models.BooleanField(default=False)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
