# Generated by Django 5.2.9 on 2026-01-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_services', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicontentlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content_logs', to='products.product'),
        ),
        migrations.AddField(
            model_name='aicontentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to='products.product'),
        ),
    ]
